/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-error-container": "#93000a",
        "on-primary-fixed": "#001847",
        "inverse-on-surface": "#f0f1f2",
        "inverse-surface": "#2e3132",
        "surface-variant": "#e1e3e4",
        "tertiary": "#005149",
        "surface-container-highest": "#e1e3e4",
        "on-primary": "#ffffff",
        "secondary-container": "#fd8b00",
        "surface-container-lowest": "#ffffff",
        "outline-variant": "#c3c6d6",
        "on-surface-variant": "#424654",
        "tertiary-fixed": "#63f9e8",
        "on-primary-container": "#ccd8ff",
        "on-secondary-fixed": "#2f1500",
        "on-primary-fixed-variant": "#0040a1",
        "surface": "#f8f9fa",
        "primary": "#0040a1",
        "on-tertiary-fixed": "#00201d",
        "surface-container-high": "#e7e8e9",
        "primary-fixed": "#dae2ff",
        "surface-bright": "#f8f9fa",
        "on-background": "#191c1d",
        "on-secondary": "#ffffff",
        "primary-fixed-dim": "#b2c5ff",
        "surface-container-low": "#f3f4f5",
        "primary-container": "#0056d2",
        "on-secondary-fixed-variant": "#6e3900",
        "secondary": "#904d00",
        "on-tertiary-container": "#58f0de",
        "on-surface": "#191c1d",
        "on-tertiary": "#ffffff",
        "surface-tint": "#0056d2",
        "on-tertiary-fixed-variant": "#005049",
        "error": "#ba1a1a",
        "surface-dim": "#d9dadb",
        "outline": "#737785",
        "tertiary-fixed-dim": "#3edccc",
        "background": "#f8f9fa",
        "on-secondary-container": "#603100",
        "surface-container": "#edeeef",
        "inverse-primary": "#b2c5ff",
        "on-error": "#ffffff",
        "secondary-fixed": "#ffdcc3",
        "tertiary-container": "#006b62",
        "error-container": "#ffdad6",
        "secondary-fixed-dim": "#ffb77d",
        "background-light": "#f6f7f8",
        "background-dark": "#101c22"
      },
      fontFamily: {
        "display": ["Plus Jakarta Sans", "sans-serif"],
        "body-md": ["Plus Jakarta Sans", "sans-serif"],
        "h3": ["Plus Jakarta Sans", "sans-serif"],
        "label-md": ["Plus Jakarta Sans", "sans-serif"],
        "h1": ["Plus Jakarta Sans", "sans-serif"],
        "caption": ["Plus Jakarta Sans", "sans-serif"],
        "body-lg": ["Plus Jakarta Sans", "sans-serif"],
        "h2": ["Plus Jakarta Sans", "sans-serif"]
      },
      fontSize: {
        "body-md": ["16px", {"lineHeight": "1.6", "letterSpacing": "0", "fontWeight": "400"}],
        "h3": ["24px", {"lineHeight": "1.4", "letterSpacing": "0", "fontWeight": "600"}],
        "label-md": ["14px", {"lineHeight": "1.2", "letterSpacing": "0.05em", "fontWeight": "600"}],
        "h1": ["48px", {"lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "caption": ["12px", {"lineHeight": "1.4", "letterSpacing": "0", "fontWeight": "400"}],
        "body-lg": ["18px", {"lineHeight": "1.6", "letterSpacing": "0", "fontWeight": "400"}],
        "h2": ["32px", {"lineHeight": "1.3", "letterSpacing": "-0.01em", "fontWeight": "700"}]
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "base": "8px",
        "sm": "12px",
        "xl": "80px",
        "xs": "4px",
        "md": "24px",
        "margin-mobile": "16px",
        "margin-desktop": "64px",
        "lg": "48px",
        "gutter": "24px"
      }
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
}